### ISSUE TITLE
Enhance User Experience by Adding an Email Icon to EmailField Component

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/GemsFX#106]
### Description
Currently, the EmailField presents itself as a standard text input field. However, this design may not be immediately intuitive for all users, especially in contexts where the field's purpose is not explicitly stated. Users might take additional time to realize that they are required to enter an email address in this field.

### Suggested Enhancement
To make the EmailField more user-friendly and intuitive, I propose adding an email icon to the left side of the text input field. This visual cue can instantly communicate the field's intended use without relying on additional textual explanations.

![image](https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/75261429/b9cfe930-a661-41e6-a4ab-7441333c82ea)

![image](https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/75261429/0404092f-504a-4caf-877b-62b36019991a)

**Comment by dlemmermann** [comment]
Looks good, make it so.
