### ISSUE TITLE
InfoCenterView configuration in the wiki

### ISSUE THREAD

**Issue by Moubassher** [dlsc-software-consulting-gmbh/GemsFX#109]
It would be great if the InfoCenterView's configuration was added to the wiki. I'm learning how to do it through trial and error, but would be awesome.
Excellent library, btw!

**Comment by dlemmermann** [comment]
Maybe this is something you could contribute?

**Comment by Moubassher** [comment]
Okay, I should give it a try.

**Comment by dlemmermann** [comment]
Docs were added by @leewyatt https://github.com/dlsc-software-consulting-gmbh/GemsFX/wiki/Notification-Center-Guide

**Comment by Moubassher** [comment]
I am terribly sorry I couldn't follow through. My country got caught in a
conflict and I've had no stable internet access ever since. Sorry again
