### ISSUE TITLE
Feature Request: Make Specific Dates Unselectable in Calendar Picker

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/GemsFX#126]
Description:
I would like to propose a new feature for our calendar picker component that allows us to make specific dates unselectable. This feature is particularly useful for applications where certain dates should not be available for selection due to various reasons, such as weekends, holidays, or other special occasions.

Use Case:
A common use case for this feature is in scheduling or booking systems where weekends (Saturdays and Sundays) are non-working days, and therefore, should not be selectable by the user. By making these dates unselectable, we can prevent the selection of inappropriate or unavailable dates, thereby improving the user experience and reducing the likelihood of scheduling errors.

**Comment by dlemmermann** [comment]
Sounds like a great addition. Looking forward to your PR.

**Comment by leewyatt** [comment]
This feature has been added in PR - #125.
