### ISSUE TITLE
 Add Default Enabled State for Filters in FilterView

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/GemsFX#134]
Overview:
The FilterView component currently supports the addition of multiple filters to assist users in refining their search or view criteria. This functionality greatly enhances the usability of the interface by allowing for dynamic data filtering. However, there is an important feature missing: the ability to set filters as enabled or disabled by default.

Issue Description:
In many scenarios, it's beneficial to have certain filters enabled by default when the view is loaded. This can help guide users towards viewing a more relevant subset of data without requiring immediate interaction, improving the overall user experience. As of now, FilterView lacks the capability to specify which filters should be active upon initialization.

**Comment by dlemmermann** [comment]
This has been added.
