### ISSUE TITLE
Mvn repository does not support jdk11

### ISSUE THREAD

**Issue by ljy1058318852** [dlsc-software-consulting-gmbh/GemsFX#137]
MVN  pom.xml:
`
<dependency>
            <groupId>com.dlsc.gemsfx</groupId>
            <artifactId>gemsfx</artifactId>
            <version>2.7.5</version>
        </dependency>
`

Operating environment：
jDK11

Error:
`
com/dlsc/gemsfx/ExpandingTextArea has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
`

Without changing the JDK, what should I do?

**Comment by dlemmermann** [comment]
Yes, GemsFX moved to Java 17 .... if you have to stay on 11 then I would suggest that you fork the repository and maintain a Java 11 version of it. Another option would be to simply copy the controls that you use into your project. Apache 2 license allows you to do that.

**Comment by ljy1058318852** [comment]
Thanks~
