### ISSUE TITLE
How to attach a textfield to numeric keyboard of GemsFX keyboard in KeyboardPane?

### ISSUE THREAD

**Issue by VISHNUVIKAS007** [dlsc-software-consulting-gmbh/GemsFX#14]
I tried to use the GemsFX keyboard for one of my projects and I liked its implementation. I would like to know how did you assign a text field to a numeric keyboard?

**Comment by dlemmermann** [comment]
The keyboard has been moved into its own project. Please take a look at KeyboardFX. Also, the code for the numeric keyboard is there. Take a look at the demo apps.
