### ISSUE TITLE
Month Dropdown Button Not Immediately Visible When showMonthDropdownProperty Set to True

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/GemsFX#142]
When setting the showMonthDropdownProperty to true on the CalendarView component, the expected Month Dropdown Button does not appear immediately. Instead, it requires additional actions such as navigating to a previous or next month to trigger a refresh, after which the Month Dropdown Button becomes visible.
<img width="830" alt="image" src="https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/75261429/b3c7c330-658d-480b-b35c-2593037ea2ac">

**Comment by dlemmermann** [comment]
Yes, I recently noticed this too and forgot about it. Good catch!
