### ISSUE TITLE
Proposal to Evaluate and Refine Properties in CalendarView

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/GemsFX#143]
This proposal addresses several  issue in the CalendarView component. Our aim is to streamline the component and enhance clarity for developers.

Redundant Property Usage:

The disableMonthDropdownButtonProperty and disableYearDropdownButtonProperty are redundant as their functionality is effectively managed by other properties like monthSelectionViewEnabledProperty.
<img width="814" alt="image" src="https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/75261429/3c762928-c1e1-4d4f-9b01-8dec06cf7513">

Unnecessary Binding Dependencies:

The binding of yearSpinnerBox.visibleProperty() to showYearDropdownProperty is unnecessary because dropdown visibility is controllable through view.setShowMonthDropdown(false), and customization options allow the monthDropdownArrowButton to diverge from being a typical arrow button. This dependency could be removed to simplify component behavior.
<img width="546" alt="image" src="https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/75261429/b2793745-f7d5-413a-9e95-de8ddd13fd5a">

Redundant Mouse Click Event Handlers:

The button used as the graphic in dateLabel has its own setOnMouseClick event handler, which is redundant because dateLabel already handles mouse clicks with similar logic. This redundancy can be removed to streamline interactions and reduce code complexity.

```java
yearDropdownArrowButton.setOnMouseClicked(evt -> viewMode.set(ViewMode.YEAR));

yearLabel.setGraphic(yearDropdownArrowButton);

 yearLabel.setOnMouseClicked(evt -> {
            if (view.isYearSelectionViewEnabled()) {
                viewMode.set(ViewMode.YEAR);
            }
        });

// mothLabel & monthDropdownArrowButton also has the same problem
```

**Comment by dlemmermann** [comment]
The two properties "show month dropdown" and "enable month selection view" are not redundant as the first one shows or hides the dropdown arrow while the second one enables the month selection view in general. If NO dropdown is shown the user can still click on the month to bring up the month selection view.

**Comment by dlemmermann** [comment]
The properties "year spinner" vs. "year dropdown" could be replaced with an enum:

- YearSelectionMode.TEXT
- YearSelectionMode.SPINNER
- YearSelectionMode.DROPDOWN
