### ISSUE TITLE
other components?

### ISSUE THREAD

**Issue by Thinker888** [dlsc-software-consulting-gmbh/GemsFX#149]
Great job!Excellent native component! Can other custom components be generated? For example, the password box can display passwords, tabpane‘s header can hold other components,the menu list on the left similar to web-ui, custom pagination, and so on.
![11](https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/89960293/885d7581-2b87-497b-94a5-af11db716a08)
![00](https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/89960293/8e06e7cc-994f-410d-b420-a9f43c561d7d)
![22](https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/89960293/7d1d7e37-bbcd-4ae5-9f68-f96f36400437),

**Comment by leewyatt** [comment]
Thank you! Here's a quick update regarding your queries:

1. JavaFX’s built-in Tab component supports the setGraphic(Node node) method, which allows you to insert additional nodes as needed. 
``` java 
Tab tab = new Tab();
            tab.setText("Tab 1");
            HBox graphicNode = new HBox(new ImageView(), new Label("Label"));
            tab.setGraphic(graphicNode);
```
2. For the side menu, you can implement it using the TreeView component.
3. Regarding the other components you mentioned, we may introduce them in the future, though I cannot commit to a specific release date at this time.

If you are interested in contributing code to add these features, we would warmly welcome your involvement!

**Comment by Thinker888** [comment]
好的，大佬！非常感谢！我会根据你的建议进行尝试的。不过，tabpane的那个样式，我的想法是要实现类似idea那种的tabpane，也就是会在tabpane顶部的最右边或者最左边添加组件。大佬有什么建议吗？我将不胜感激！

**Comment by leewyatt** [comment]
@Thinker888 
1. We've create a new component called **EnhancedPasswordField**, which is quite similar to your requirements. You can test it to see if there are any bugs. If you find any bugs, please remember to let us know. Thank you!
2. If you want to extend TabPane, you typically need to override both TabPane and TabPaneSkin, mainly focusing on rewriting the skin class.

<img width="310" alt="image" src="https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/75261429/1eba4819-7563-48fa-9698-a10d688ce907">
