### ISSUE TITLE
Developer guide

### ISSUE THREAD

**Issue by sebkur** [dlsc-software-consulting-gmbh/GemsFX#15]
Hi, all this look quite nice, so I wanted to try things out on my own machine. However I am a bit stuck here.

I'm missing an introduction on how to get things started if you're not familiar with similar projects yet.

Grepping through the project I figured out that there are 6 entry points with apps that are launchable:

    KeyboardDarkApp.java
    RichTextAreaApp.java
    DrawerApp.java
    KeyboardApp.java
    EmailFieldApp.java
    FilterViewApp.java

Is there a simple way for running any of these classes that contain a `public static void main(String[])` method without starting an IDE, just using Maven? If there is it would be super helpful to list that as an example in the readme file.

Other than that, I'm totally willing to launch an IDE for testing things if Maven does not offer a simple way to run the demos. It would be very helpful if you listed the setup you know is working (that is, your own setup). Which IDE can I use, what do I have to do to start hacking on the project?

I assume Eclipse will do, but I have no idea what to do make things work there. I tried `mvn eclipse:eclipse` and imported the two projects `gemsfx` and `gemsfx-demo` into a workspace (using an OpenJDK 11). Seems like all the imports starting with `javafx.*` cannot be resolved. Is there an additional Maven task to fix this maybe? Sure I can try to figure things out using Google but let's make things easy for newbies :)

If you're not using Eclipse or not aware of how to make things work there, don't worry that's fine. I'm also willing to download a different IDE to try things. Just sharing any development setup that is known to work and reproducible steps on how to get things started would be very appreciated! Thanks a lot

**Comment by fthevenet** [comment]
I agree a quick word or two in the README on how to start the demonstrators would go a long way! ;-)

@sebkur From what I could figure out, you can launch the demonstration via Maven with the following command (from the root folder for your clone):
```
mvn javafx:run -f gemsfx-demo\pom.xml
```
Given the state of the source at the time of writing this will start the virtual keyboard demo. If you want to try out another demo, you can substitute the the `mainClass`of your choice here, in gemsfx-demo/pom.xml
``` xml
 <build>
        <plugins>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.4</version>
                <configuration>
                    <mainClass>com.dlsc.gemsfx.demo.KeyboardApp</mainClass>
                </configuration>
            </plugin>

```

There maybe a more elegant way to switch from one demonstrator to the next, but I haven't found it.

**Comment by dlemmermann** [comment]
I agree, too. If you have a good idea on how to make this easier / a good readme that we can add then please submit a pull request. I personally always use a right click / context menu / run ... menu item in IntelliJ. I do not normally launch via Maven.

**Comment by dlemmermann** [comment]
Regarding the javafx imports. All JavaFX dependencies are pulled in via the maven dependencies settings. That should really be all there is to it. Make sure to use Java 11.

**Comment by fthevenet** [comment]
> I personally always use a right click / context menu / run ... menu item in IntelliJ. I do not normally launch via Maven.

When I try to run the samples from IntelliJ the way you suggest, I get the following error:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.media not found, required by javafx.web

Process finished with exit code 1
```

I've tried with OpenJDK 14 and 11 with the same result.

**Comment by sebkur** [comment]
Great, thanks @fthevenet for figuring that out. I adapted that solution to create #16

**Comment by sebkur** [comment]
> I agree, too. If you have a good idea on how to make this easier / a good readme that we can add then please submit a pull request. I personally always use a right click / context menu / run ... menu item in IntelliJ. I do not normally launch via Maven.

Okay, then we could document IntelliJ as the recommended IDE. Still curious how to make things work in Eclipse though :thinking:
