### ISSUE TITLE
Add Timeline component.

### ISSUE THREAD

**Issue by Xiaobaishushu25** [dlsc-software-consulting-gmbh/GemsFX#180]
such as 
![`A{5FM5 XTT2PZ$5ZBW}{GK](https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/76581880/079a8adf-9c77-4324-94b7-89ba7b121520)
It can be configured in a horizontal or vertical direction, and the color of the nodes can be configured.

**Comment by leewyatt** [comment]
If I have some free time, I'm willing to give it a try. There might not be a definite completion time.

**Comment by dlemmermann** [comment]
Closing this as it is not an "issue". You guys might wanna move this to the "discussion" board.
