### ISSUE TITLE
Question: Working with ChipViews

### ISSUE THREAD

**Issue by NeoCortex97** [dlsc-software-consulting-gmbh/GemsFX#193]
Hi,
before I ask my question I will try to preface it with some explanations:
I know that I am using a component that you only developed for internal use, but I did not want to implement my own.
I have looked for some other ChipView component, but I did not find any.
I only realized that ChipView was mainly for internal use after i fully implemented my feature.

I have used your FilterView component and saw the chips that are closable. But when I implemented it in my feature, so how could I make my chips closable?

And thank you a lot for your great library.

Best regards
Neo

**Comment by dlemmermann** [comment]
Just set the "onClose" handler on the ChipView: `ChipView.setOnClose(Consumer<T> onClose)`. The consumer you set should update your data model which in return should rebuild the area of the UI that shows your chip views.

**Comment by dlemmermann** [comment]
The `ChipView` was initially designed to work with the `FilterView` but I then made it its own control to be more reusable.

**Comment by NeoCortex97** [comment]
Does adding an `onClose`-handler enable a close button?

**Comment by dlemmermann** [comment]
yes.
