### ISSUE TITLE
`ExpandingTextArea` doesn't change it's height when `Enter` handler is changed

### ISSUE THREAD

**Issue by InAnYan** [dlsc-software-consulting-gmbh/GemsFX#198]
I was writing a chat app with a chat prompt that supports sending multi-line messages.

I wrote this code:
```java
userPromptTextArea.setOnKeyPressed(keyEvent -> {
    if (keyEvent.getCode() == KeyCode.ENTER) {
        if (keyEvent.isControlDown()) {
            userPromptTextArea.appendText("\n");
        } else {
            onSendMessage();
         }
    }
});
```

What it does is this (similar to https://chatgpt.com/):
1. When user presses `Enter` key, new line is added.
2. When user presses `Ctrl+Enter` key (well, that's two keys, actually 😄), message is sent.

But, when user performs action 1 (only `Enter`), the height of `ExpandingTextArea` is not recalculated.

The component is fully functional, I can add new lines and scroll, etc., but the height is limited to 2 lines.

So:
- Is this an issue from `ExpandingTextArea` side?
- Or, maybe I should've written different logic for handling `Enter`/`Ctrl+Enter` events?

**Comment by dlemmermann** [comment]
Your description and the code contradict each other. I have a feeling you want what the code says, not what you are writing:
when the user hits ENTER the messages goes out. When the user presses CTRL+ENTER then you keep adding text lines.

**Comment by dlemmermann** [comment]
You should use an event filter for this:

```
        expandingTextArea.addEventFilter(KeyEvent.KEY_PRESSED, keyEvent -> {
            if (keyEvent.getCode() == KeyCode.ENTER) {
                if (keyEvent.isControlDown()) {
                    expandingTextArea.appendText("\n");
                } else {
                    expandingTextArea.setText("");
                    keyEvent.consume();
                    System.out.println("sending");
                }
            }
        });```
