### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by ahgpsisamex** [dlsc-software-consulting-gmbh/GemsFX#20]
Hello,

I am currently adding the pdfviewer to my app that I made in netbeans. The problem is that i get a bunch of errors when I run the app that I've made using maven with the shaded plugin.

Here are the errors:
`Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: Cannot resolve 'mdi-fullscreen'                                                                                              
Oct 15 12:56:04 raspberrypi run.sh[9867]:         at org.kordamp.ikonli.javafx.IkonResolver.resolveIkonHandler(IkonResolver.java:62)                                                                                                                            
Oct 15 12:56:04 raspberrypi run.sh[9867]:         at org.kordamp.ikonli.javafx.FontIcon.lambda$new$2(FontIcon.java:94)                                                                                                                                          
Oct 15 12:56:04 raspberrypi run.sh[9867]:         at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)`

And...

`Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: Cannot resolve 'mdi-chevron-left'                                                                                            
Oct 15 12:56:04 raspberrypi run.sh[9867]:         at org.kordamp.ikonli.javafx.IkonResolver.resolveIkonHandler(IkonResolver.java:62)                                                                                                                            
Oct 15 12:56:04 raspberrypi run.sh[9867]:         at org.kordamp.ikonli.javafx.FontIcon.lambda$new$2(FontIcon.java:94)                                                                                                                                          
Oct 15 12:56:04 raspberrypi run.sh[9867]:         at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)                                                                                                           
Oct 15 12:56:04 raspberrypi run.sh[9867]:         at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)                                                                                                                    
Oct 15 12:56:04 raspberrypi run.sh[9867]:         at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)  `

Guess the errors are from loading the icons.

This is my pom.xml file (attached)

[pom.zip](https://github.com/dlsc-software-consulting-gmbh/GemsFX/files/5387034/pom.zip)

And I run the project with `java -Djdk.gtk.version=2 -Dcom.sun.javafx.virtualKeyboard="javafx" -jar shaded.jar --module-path /usr/share/openjfx/lib --add-modules=javafx.controls,javafx.fxml                                                                                   
`
I can open the file with no problems, only the missing icons but they function correctly.

Can you please help me?

**Comment by dlemmermann** [comment]
You have to add the "material icon set" from the Ikonli project.

**Comment by dlemmermann** [comment]
Sorry for the late response.

**Comment by dlemmermann** [comment]
Please be aware that the keyboard has been moved to its own project called "KeyboardFX".

**Comment by ahgpsisamex** [comment]
Thanks!
