### ISSUE TITLE
Localization, custom CSS, components

### ISSUE THREAD

**Issue by storkeu** [dlsc-software-consulting-gmbh/GemsFX#21]
Hi, very interested in PDFView. Works really well, but saddly, it seems not to be localizable. Is there a plan to Externalize Strings?
Also, if the presentation layer was in FXML with components for navigation bar, thumbnails, search bar, etc, and we could set de css file, that would help a lot, in order to integrate this cool tool in our apps. I am not very experienced in JavaFX, perhaps there is a solution as is but I can't figure it out.
Thanks

**Comment by dlemmermann** [comment]
This is open source. Feel free to add i18n to this project. Ideally by something like https://www.transifex.com (free for open source project AFAIK).

**Comment by dlemmermann** [comment]
The ControlsFX project uses Transifex and it works very well there. It has support for a lot of languages.

**Comment by dlemmermann** [comment]
But it's really only tooltips. Those bothering you?

**Comment by dlemmermann** [comment]
i18n will be added now by me as a paying customer asked for it. So will do that. It will be a resource bundle inside the project, not Transifex. Let's keep it simple.
