### ISSUE TITLE
Duration Picker - Setting duration to zero does not clear all fields.

### ISSUE THREAD

**Issue by sten-navie** [dlsc-software-consulting-gmbh/GemsFX#23]
Running the picker demo. If I have values in multiple slots e.g. 22h:03m, I have to press "Update with zero duration" multiple times? Is this the intended behavior? From looking at the code I thought this would set the total duration to zero, zeroing all fields.

**Comment by dlemmermann** [comment]
Nope, not the intended behaviour :-) Fixed it.
