### ISSUE TITLE
Duration Picker - Localization.

### ISSUE THREAD

**Issue by sten-navie** [dlsc-software-consulting-gmbh/GemsFX#25]
Would it be possible to have the short and long label texts in resource files? People use our software in other languages than en. We can do the actual translations ourselves as long as the component is able to pick them up from resource-files.

**Comment by dlemmermann** [comment]
resource bundle added ... only a few keys ... I can add the finish one if you send it to me. These are the properties needed: 

unit.long.days=days
unit.long.hours=hours
unit.long.minutes=minutes
unit.long.seconds=seconds
unit.long.millis=millis

unit.short.days=d
unit.short.hours=h
unit.short.minutes=m
unit.short.seconds=s
unit.short.millis=ms

popup.unit.title.days=Days
popup.unit.title.hours=Hours
popup.unit.title.minutes=Minutes
popup.unit.title.seconds=Seconds
popup.unit.title.millis=Millis
