### ISSUE TITLE
Duration Picker - RFE - Wrapping in the popup. 

### ISSUE THREAD

**Issue by sten-navie** [dlsc-software-consulting-gmbh/GemsFX#26]
Is it possible to roll the values in the popup, e.g. wrapping 00 seconds to 59 if one goes "up"? I instinctively tried to do this with the mouse-wheel. Days being the exception, as we might not have a upper limit there.

**Comment by dlemmermann** [comment]
Do you think we should use the Picker control for that? A trimmed down version with a more lightweight appearance.

**Comment by sten-navie** [comment]
> 
> 
> Do you think we should use the Picker control for that? A trimmed down version with a more lightweight appearance.

Yes! That could work!

**Comment by dlemmermann** [comment]
OK, will add it.

**Comment by dlemmermann** [comment]
Was implemented as a picker.
