### ISSUE TITLE
TimePicker Popup misses minute 59

### ISSUE THREAD

**Issue by joehei** [dlsc-software-consulting-gmbh/GemsFX#27]
Hi, 
first many thanks for contributing this control.

I found a small issue. The Popup does not contain minute 59.

![image](https://user-images.githubusercontent.com/46645618/100332815-237d8b80-2fd2-11eb-8331-653dcda792e5.png)

**Comment by dlemmermann** [comment]
Good catch. I fixed it. Will be available in next release.
