### ISSUE TITLE
error installing the maven project

### ISSUE THREAD

**Issue by alvazai** [dlsc-software-consulting-gmbh/GemsFX#35]
Hello,

I was trying to install GemsFX upon recommendation of Florian Kirmaier, who I guess is one of the developers of JPro framework. According to him, I should be able to use GemsFX dialogs in JavaFX UI inside web pages. I got this error:

Failed to collect dependencies at com.dlsc.gemsfx:gemsfx:jar:1.29.2 -> com.dlsc.unitfx:unitfx:jar:1.0.8: Failed to read artifact descriptor for com.dlsc.unitfx:unitfx:jar:1.0.8: Could not transfer artifact com.dlsc.unitfx:parent:pom:1.0.8 from/to bintray-dlsc-oss-repository (https://dl.bintray.com/dlsc-oss/repository): Authorization failed for https://dl.bintray.com/dlsc-oss/repository/com/dlsc/unitfx/parent/1.0.8/parent-1.0.8.pom 403 Forbidden -> [Help 1]

Could you please advice how to work around this problem?

Thanks!
Alexey Zaitsev

**Comment by dlemmermann** [comment]
Hi Alexey, yes ... the latest release of GemsFX is referencing a version of UnitFX that does not exist on Maven Central but only on BinTray. Since BinTray is no longer available you can not use it. Please try an older version. Right now I do not know which version will eventually start working, so you have to do a little try and error. Sorry about that. Once I have figured out how to deploy to Maven Central I will provide a new version.

**Comment by alvazai** [comment]
Dirk, just to update you, ver. 1.20.0 linked fine. There may be other problems down the road, but there is nice progress :-)

All the best,
Alexey

**Comment by lepton-gmbh** [comment]
Same error. 4h trying to resolve it.

**Comment by alvazai** [comment]
Lepton-gmbh, as Dirk mentioned you just need to use an earlier version. In fact, to update, the version working for me is 1.27.0.

**Comment by lepton-gmbh** [comment]
Thx very much Alexey.
This was a great job Dirk.

**Comment by reevee-codes** [comment]
1.0.6 worked for me for  
<groupId>com.dlsc.unitfx</groupId>
    <artifactId>unitfx</artifactId>
and using java 17.

Thank you so much for your hard work, these are beautiful! :) ♥♥♥

**Comment by joehei** [comment]
Hi Dirk,
could you please increase prio on this ;-) 

You have such a cool lib, but at the moment not usable.

**Comment by dlemmermann** [comment]
Released version 1.30.0 and this should all be resolved now.
