### ISSUE TITLE
MVN Repository lists Version 1.29.2 already 

### ISSUE THREAD

**Issue by timoreichen** [dlsc-software-consulting-gmbh/GemsFX#37]
which causes: Failed to collect dependencies at com.dlsc.gemsfx:gemsfx:jar:1.29.2 -> com.dlsc.unitfx:unitfx:jar:1.0.8:

Maybe the wrong place to report then just delete the issue.

**Comment by dlemmermann** [comment]
Yeah, there was some chaos. I forgot to release unitfx parent pom to Maven Central. This should all be working now with release 1.30.0 of GemsFX and 1.0.9 of UnitFX.
