### ISSUE TITLE
JavaFX application containing PDFView node wont exit

### ISSUE THREAD

**Issue by PrimosK** [dlsc-software-consulting-gmbh/GemsFX#4]
I've noticed that JavaFX application containing `PDFView` node wont exit properly.

Steps to reproduce:
1. Run `com.dlsc.gemsfx.demo.PDFViewApp`.
2. Try to close the application.

Expected result:
_The application should exit immediately._

Actual result:
_Application won't exit._

**Comment by dlemmermann** [comment]
Fixed by marking threads created by executor service as "daemon" threads.
