### ISSUE TITLE
GemsFX 1.29.1 - SearchTextField //missing export in module-info

### ISSUE THREAD

**Issue by todayifeeltired** [dlsc-software-consulting-gmbh/GemsFX#47]
Hello :)
When using the SearchTextFIeld i get the message "module com.dlsc.gemsfx does not export com.dlsc.gemsfx.skins to module javafx.fxml". I saw that this has been fixed in newer releases, but i dont want to upgrade from JDK 11. 
Is it possible/planned to fix this?
Thanks in advance

**Comment by dlemmermann** [comment]
You don't have to upgrade ... GemsFX is (should be) Java 11 compatible. Isn't it?

**Comment by dlemmermann** [comment]
I checked ... it is targeting 11.

```
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>11</release>
                    <source>11</source>
                    <target>11</target>
                </configuration>
```

**Comment by dlemmermann** [comment]
Yes, older versions used the wrong Java version. Please use 1.41

**Comment by dlemmermann** [comment]
Actually 1.42.

**Comment by todayifeeltired** [comment]
i get the error also for 1.41 and 1.42 :/

**Comment by dlemmermann** [comment]
Are you building the project yourself or downloading from Maven central?

**Comment by dlemmermann** [comment]
You might also consider using the enforcer plugin in your pom.xml file (hope you use Maven). This way you get told which dependency is using what.

```xml
<properties>
    <java.version>11</java.version>
</properties>

```

```xml
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>3.0.0</version>
                </plugin>
               .....
```

```xml
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>extra-enforcer-rules</artifactId>
                        <version>1.5.1</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <rules combine.children="override">
                                <requireMavenVersion>
                                    <version>${maven.version}</version>
                                </requireMavenVersion>
                                <requireJavaVersion>
                                    <version>${java.version}</version>
                                </requireJavaVersion>
                                <enforceBytecodeVersion>
                                    <maxJdkVersion>${java.version}</maxJdkVersion>
                                </enforceBytecodeVersion>
                                <dependencyConvergence/>
                                <requireUpperBoundDeps/>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by todayifeeltired** [comment]
yes, i am using maven and i am downloading gemsfx via maven.
i´ll give the enforcer-plugin a shot

**Comment by todayifeeltired** [comment]
the enforcer plugin says it requires upper bound dependencies for some, but i dont understand how to fix the gemsfx issue with it.
i´m sure that is has to do something with the gemsfx-ersion because the clean install works with gemsfx 1.29.1.
or am i wrong with something?

**Comment by todayifeeltired** [comment]
it looks correct to me to.
I made a new JavaFX project with the Intellij-Template

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>demo</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.8.1</junit.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>11.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>11.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.dlsc.gemsfx</groupId>
            <artifactId>gemsfx</artifactId>
            <version>1.42</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <executions>
                    <execution>
                        
                        <id>default-cli</id>
                        <configuration>
                            <mainClass>com.example.demo/com.example.demo.HelloApplication</mainClass>
                            <launcher>app</launcher>
                            <jlinkZipName>app</jlinkZipName>
                            <jlinkImageName>app</jlinkImageName>
                            <noManPages>true</noManPages>
                            <stripDebug>true</stripDebug>
                            <noHeaderFiles>true</noHeaderFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>`

I added gemsfx 1.42 as a dependency.

Maven clean install still claims "Unsupported major.minor version 56.0" :(

**Comment by dlemmermann** [comment]
Try excluding this dependency from GemsFX. It is a multi-version JAR file that gets pulled in because of GemsFX dependency to UnitFX.

<img width="436" alt="Screenshot 2022-03-31 at 15 21 12" src="https://user-images.githubusercontent.com/9534301/161064499-c7dbf9de-6de5-40b3-806b-8892a5e20414.png">

**Comment by dlemmermann** [comment]
you can also get around it by using a newer JDK to compile ... Simply use a JDK > 11 and everything works fine. Since you specify the Java version target in the pom.xml file the compiled code will be Java 11 compatible. I just realised that this is the reason that I did not notice this problem. I use JDK 17 or 18.

**Comment by todayifeeltired** [comment]
okay but then i need to ugrade from jdk 11. idk i like to have the same jdk as the target i´m trying to compile.

**Comment by dlemmermann** [comment]
Maybe you find some maven docs on how to exclude code inside multi-version jar files that require a newer java version?

**Comment by todayifeeltired** [comment]
should it be working if i exclude the whole tech.units:indriya:2.1.2 or only the java 12 and 14 parts?

**Comment by dlemmermann** [comment]
Not sure you can exclude parts individually. Probably the whole thing needs to be excluded.

**Comment by dlemmermann** [comment]
gemsfx has a dependency to UnitFX and UnitFX has the dependency to tech.units:indriya. Some of the controls inside GemsFX require controls from UnitFX.

**Comment by dlemmermann** [comment]
Sponsoring is available here: https://github.com/dlsc-software-consulting-gmbh

**Comment by todayifeeltired** [comment]
solution:
`<dependency>
            <groupId>com.dlsc.gemsfx</groupId>
            <artifactId>gemsfx</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>tech.units</groupId>
                    <artifactId>indriya</artifactId>
                </exclusion>
            </exclusions>
            <version>1.42</version>
        </dependency>`
