### ISSUE TITLE
TimePicker and SceneBuilder

### ISSUE THREAD

**Issue by kromar777** [dlsc-software-consulting-gmbh/GemsFX#51]
Hello and thanks for great library!

Is it possible to use a TimePicker with SceneBuilder? I tried and SceneBuilder doesn't allow timepicker dragging on the form. It can be added by editing .fxml though and it works but again scene builder won't open .fxml with timepicker.

**Comment by dlemmermann** [comment]
I never tried that. I am not much of a SceneBuilder user. I write my FXML manually or use the Java API. Please google what the requirements are for adding a control to SceneBuilder.

**Comment by cpreisler** [comment]
Hello, I ran into this issue yesterday. To fix it, I built gemsFx using the maven-shade-plugin. I then added the fat jar that was created to SceneBuilder, and now I can drag and drop the TimePicker onto the form and open the fxml file after it is added. 

SceneBuilder was silently crashing with a NoClassDefFoundError for org/kordamp/ikonli/javafx/FontIcon. I was able to figure that out by building scenebuilder locally and running it from the command line. SceneBuilder then produced a log file that gave enough info to find the problem.

Here is the shade plugin that was added to the gemsfx POM. The transformer is the key to making this work.

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <excludes>
                                    <exclude>org.openjfx:*</exclude>
                                </excludes>
                            </artifactSet>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <outputFile>target/gemsfx-${project.version}-all.jar</outputFile>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>    
```

**Comment by dlemmermann** [comment]
can you submit a PR for this please?

**Comment by dlemmermann** [comment]
I just tried that and it did not work .... hmmmm

**Comment by dlemmermann** [comment]
yes I did
