### ISSUE TITLE
FilterView - CSS Selector for Search-Text-Field

### ISSUE THREAD

**Issue by todayifeeltired** [dlsc-software-consulting-gmbh/GemsFX#52]
Hi there,

i cant select/access the search-text-field from the FilterView via css.

i tried:
`.filter-view .search-field {
    -fx-background-color: red;
}

.search-field {
    -fx-background-color: red;
}

.search-text-field {
    -fx-background-color: red;
}`

have seen the first two in one of your commits 3 months ago and gave them a shot after .search-text-field didnt work in case you are wondering why i brought them up.

I have also seen that there is an CSS Selector for an item-count label
.filter-view .filters .item-count-label {
    -fx-font-size: 14px;
}

But i havent found the feature (neither in the demo nor in my implementation).

**Comment by leewyatt** [comment]
Hi,

To properly style the SearchTextField using CSS, you'll need to reference the layout structure as defined in the **FilterViewSkin**. You can use the following CSS selector to target it:
`.filter-view > .filter-container .search-text-field {
    -fx-background-color: rgba(173, 216, 230, 0.52);
}
`

![image](https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/75261429/5ea48a25-9af4-4c9f-ab57-222c46d3f28c)
