### ISSUE TITLE
SearchTextField in Jar - Icons missing

### ISSUE THREAD

**Issue by todayifeeltired** [dlsc-software-consulting-gmbh/GemsFX#53]
Hi there,
when i package my JavaFX application via:

`<plugin>
            <artifactId>maven-assembly-plugin</artifactId>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                    <configuration>
                        <archive>
                            <manifest>
                                <mainClass>
                                    .Main
                                </mainClass>
                            </manifest>
                            <manifestEntries>
                                <Multi-Release>true</Multi-Release>
                            </manifestEntries>
                        </archive>
                        <descriptorRefs>
                            <descriptorRef>jar-with-dependencies</descriptorRef>
                        </descriptorRefs>
                    </configuration>
                </execution>
            </executions>
        </plugin>`

and use it via java -jar then the jar doenst contain the "search" and "trash" icon.
I also get the error: 
Cannot resolve mdi-magnify which is the search icon.

**Comment by fusionart** [comment]
Hello,

I am having similar issue with "mdi" icon pack used from GemsFX.

When I start the app from IntelliJ everything is working correctly.

But when I build a fatjar using "mvn compile package" command and maven-shade-plugin and run it using "java -jar", I get this errors on runtime:
Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: Cannot resolve 'mdi-close'
or 
Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: Cannot resolve 'mdi-clock'

The second issue is causing problems loading the stage with the Time Picker. It is making it almost unusable.

I am running the app on Ubuntu 22.04, JDK openjdk 18.0.2 2022-07-19 ,OpenJDK Runtime Environment Temurin-18.0.2+9 (build 18.0.2+9) and JavaFX 18.

Nick
P.S. Great JavaFX components, by the way.

**Comment by dlemmermann** [comment]
You might wanna contact Andreas Almiray via the ikonli project. Maybe this is an issue he is familiar with. This is definitely not a GemsFX issue but a build problem AFAIK (shade plugin?), hence closing this issue.
