### ISSUE TITLE
Highlights misalignment

### ISSUE THREAD

**Issue by PrimosK** [dlsc-software-consulting-gmbh/GemsFX#6]
In some cases the search highlights are misaligned. 

For example - searching for "dropbox" in this document:

[Get Started with Dropbox.pdf](https://github.com/dlsc-software-consulting-gmbh/GemsFX/files/4443523/Get.Started.with.Dropbox.pdf)

... results in highlights being misplaced (see second and third match on 2. page):

![missplaced-highlight-example](https://user-images.githubusercontent.com/1519324/78658160-1a686e80-78ca-11ea-94cd-9de478acbbc4.png)

**Comment by dlemmermann** [comment]
Fixed and verified.
