### ISSUE TITLE
Unable to find StripView control

### ISSUE THREAD

**Issue by conradbekondo** [dlsc-software-consulting-gmbh/GemsFX#66]
I can clearly see the code for StripView in gemsfx on GitHub, but I can't find it in the code???

- On GitHub
![image](https://user-images.githubusercontent.com/112887424/228311231-2331a3ec-2ace-41b9-8aa4-4d9e48728a59.png)

- Dependency
![image](https://user-images.githubusercontent.com/112887424/228311321-284fc4fd-d748-4188-9841-2005c7e052f5.png)

- In code
![image](https://user-images.githubusercontent.com/112887424/228311543-6d1c3b64-acc4-468f-8a9b-b4bbaee40b0b.png)

Am I using the wrong version??

**Comment by dlemmermann** [comment]
yes ... we are at 1.72.0 these days. Welcome to the future! :-)
