### ISSUE TITLE
log4j-slf4j-impl version stopped by my enforcer plugin

### ISSUE THREAD

**Issue by trixon** [dlsc-software-consulting-gmbh/GemsFX#67]
When I updated my dependency from 1.67.0 to 1.71.0 I could not build my project with an active enforcer to avoid log4shell.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.2.1:enforce (ban-bad-log4j-versions) on project mapton-api: 
[ERROR] Rule 0: org.apache.maven.enforcer.rules.dependency.BannedDependencies failed with message:
[ERROR] org.mapton:mapton-api:nbm:3.1.0-SNAPSHOT
[ERROR]    com.dlsc.gemsfx:gemsfx:jar:1.71.0
[ERROR]       org.apache.logging.log4j:log4j-slf4j-impl:jar:2.14.1
[ERROR]
```

Are there any reason for using 2.14.1?

**Comment by dlemmermann** [comment]
no

**Comment by dlemmermann** [comment]
I usually have dependabot alerts enabled but this dependency got pulled in via the parent pom and there the alerts were not enabled. Did so now .... looking forward to many alerts :-)

**Comment by dlemmermann** [comment]
Updated to 2.20.0.
