### ISSUE TITLE
Add event which gets fired when the SearchField has commited

### ISSUE THREAD

**Issue by conradbekondo** [dlsc-software-consulting-gmbh/GemsFX#69]
It would be helpful to be able to know when the user has selected a search suggestion when a `SearchField`'s `commit` has been called. It is currently not possible to react to this by listening to when the enter key has been released, because the event is being consumed.

**Comment by dlemmermann** [comment]
A pull request would be much appreciated.

**Comment by dlemmermann** [comment]
This was changed again. You can now register an "onCommit" handler.
