### ISSUE TITLE
Application not building when including GemsFX as a dependency

### ISSUE THREAD

**Issue by reardenSteel1964** [dlsc-software-consulting-gmbh/GemsFX#72]
I've included the following in my application's build.gradle file:

implementation group: 'com.dlsc.gemsfx', name: 'gemsfx', version: '1.72.0'

When building my application with the above dependency, the following error is generated:

Could not find one.jpro.jproutils:tree-showing:0.2.2

Any insight you can provide into how this can be resolved would be greatly appreciated. 

Many thanks for all the great work you've done.

Brian

**Comment by dlemmermann** [comment]
You need to add the jpro repository to your project as well. You can find it in the gemsfx project's pom files.

**Comment by dlemmermann** [comment]
```
    <repositories>
        <repository>
            <id>sandec</id>
            <url>https://sandec.jfrog.io/artifactory/repo</url>
        </repository>
    </repositories>
```
