### ISSUE TITLE
Having problems with jproutils

### ISSUE THREAD

**Issue by gleidsonmt** [dlsc-software-consulting-gmbh/GemsFX#83]
I copied the short implementation for gradle in maven, but when I tried to build I had this error message, 

Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find one.jpro.jproutils:tree-showing:0.2.2.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/one/jpro/jproutils/tree-showing/0.2.2/tree-showing-0.2.2.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > com.dlsc.gemsfx:gemsfx:1.76.0

**Comment by dlemmermann** [comment]
You need to add the JPro repository to your list of repositories. The JPro stuff is not on Maven Central. You can find the location of their repo in one of the pom.xml files.

**Comment by gleidsonmt** [comment]
Worked as expect, thanks for attention
