### ISSUE TITLE
Issue with CSS file path in getUserAgentStylesheet method

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/GemsFX#85]
### Description
When utilizing the getUserAgentStylesheet method from the **TreeNodeCell** class in other projects, it fails to locate the "tree-view.css" file, resulting in an error. Here is the problematic snippet:

```java
@Override
public String getUserAgentStylesheet() {
    return getClass.getResource("tree-view.css").toExternalForm();
}
```

The issue can be resolved by updating the method to:
```java
@Override
public String getUserAgentStylesheet() {
    return TreeNodeCell.class.getResource("tree-view.css").toExternalForm();
}
```

**Comment by dlemmermann** [comment]
Yep, never use getClass().getResource() ..... as it will then point to a completely different location when the class gets subclassed.
