### ISSUE TITLE
Phone Number Field

### ISSUE THREAD

**Issue by gldiazcardenas** [dlsc-software-consulting-gmbh/GemsFX#88]
**Goal**: Build a nice input field to enter international phone numbers.
**Requirements**:
- Provide country code selection by typing the country name.
- Use masking technique to make explicit reference of the phone number format, so users have an idea of what's expected input.

**References**:
- Standard E.164: https://en.wikipedia.org/wiki/E.164
- Telephone numbers in UK: https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom
- Example 1: https://uxplanet.org/phone-number-field-design-best-practices-23957cbd86d5
- Example 2: https://catamphetamine.gitlab.io/react-phone-number-input/?
- How to in HTML: https://www.twilio.com/blog/international-phone-number-input-html-javascript
- List of country codes: https://en.wikipedia.org/wiki/List_of_country_calling_codes
- Formatting: https://blog.insycle.com/phone-number-formatting-crm
- Google Tool: 
-- https://github.com/google/libphonenumber
-- https://libphonenumber.appspot.com/

**Comment by dlemmermann** [comment]
Love the example and the references.

**Comment by gldiazcardenas** [comment]
This is a UML representation of what the control could be:

![PhoneNumberField drawio](https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/1269062/1c0ce693-ccbf-4794-8bde-c1aa05987e86)


- The component is going to delegate the responsibility of restricting the user's input to an interface called _Mask_.
- A Mask is a format specific phone number representation, it can vary from country to country (or world zones).  The important aspect is that formats are changing all the time, and also depends on the system the developer is building.  This way it can be customized according to the needs.

### PhoneNumberField - Model
- value: StringProperty -> is the representation of the number according to the Mask provided.  This is editable field.
- countryCode: IntegerProperty -> the code of the country selected.  The developer can setup a default initial country, and it should be reflected once the control shows up.
- number: LongProperty -> Read only numeric representation of the value.
- valid: BooleanProperty -> Read only validation indicator.  The Mask will validate the value everytime it changes, and will update this property.

**Comment by dlemmermann** [comment]
Why does it subclass ComboBoxBase?

**Comment by gldiazcardenas** [comment]
We use to extend ComboBoxBase when it pops up some control, in this case the country selection would be a popup.

**Comment by dlemmermann** [comment]
Yes, but only that one element ... which will be an "inner" element of the skin of the field. There I would expect you to use a standard ComboBox and not extend from the base class.

**Comment by gldiazcardenas** [comment]
I see..  well I just followed the current standard in the code.. CalendarPicker, DurationPicker, TimePicker, YearMonthViewPicker..  all them extend ComboBoxBase.   So if I understand correctly, you want the PhoneNumberField extend from Control class?..   you wrote "There I would expect"..  that "There" means the skin?

**Comment by dlemmermann** [comment]
Yes, subclass Control and use a combobox inside the skin of the control for the dropdown capabilities of the country selection.

**Comment by dlemmermann** [comment]
I haven't checked if you have done this already, but please make sure that the node that displays the country flag can be configured via a factory. In other words: please provide a callback that returns a node for a given country. This way the control can be completely adjusted to different look and feels.

**Comment by gldiazcardenas** [comment]
Initially I implemented this though out the interface "CountryCallingCode", however, that mechanism is kind of odd, and would imply more complexity, so I followed the regular jfx pattern (as per your suggestion) and provided a callback to replace the flag with an externally provided Node.

**Comment by dlemmermann** [comment]
This control was moved to its own project called PhoneNumberFX.
